// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbsjjqjeyypbaqrhuhvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZic2pqcWpleXlwYmFxcmh1aHZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMTc5MTIsImV4cCI6MjA2Mzg5MzkxMn0.Ng95w0_22cenpI6IPiOLotvP8TzGxa9jmLTpy4uo4rY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);